# Generated by Django 3.0.7 on 2020-08-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='カテゴリー名')),
                ('due', models.DateField(blank=True, null=True, verbose_name='期限日')),
            ],
            options={
                'verbose_name_plural': 'TodoCategory',
                'db_table': 'todo_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id',
                 models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='todo.TodoCategory')),
                ('name', models.CharField(help_text='Todoタイトルを入力してください', max_length=64, verbose_name='Todoタイトル名')),
                ('description', models.CharField(help_text='Todo内容を入力してください', max_length=128, verbose_name='内容')),
                ('due_date', models.DateField(blank=True, help_text='期日を入力してください', verbose_name='期限日')),
                ('created_at', models.DateTimeField(verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='更新日時')),
                ('todo_category_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'TodoList',
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
