# Generated by Django 3.0.7 on 2020-08-04 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
