# Generated by Django 3.1 on 2020-08-06 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0002_auto_20200804_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True, 'verbose_name_plural': 'Todo'},
        ),
    ]
