# Generated by Django 3.0.7 on 2020-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodosLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Todoタイトルを入力してください', max_length=64, verbose_name='Todoタイトル名')),
                ('description', models.CharField(help_text='Todo内容を入力してください', max_length=128, verbose_name='内容')),
                ('due_date', models.DateField(auto_now_add=True, verbose_name='期限日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Todo',
            },
        ),
    ]
